serviceAccount: wi-s-blue-blue-health-go-srv

deployments:
  app:
    replicaCount: 2
    containers:
      app:
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
    strategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 2
    nodeSelector:
      cloud.google.com/gke-nodepool: general-n2-standard-2

migrations:
  app:
    containers:
      proxy:
        args:
          - |
            /cloud_sql_proxy -ip_address_types=PRIVATE -instances=XXX=tcp:5432 &
            CHILD_PID=$!
            (while true; do if [[ -f "/lifecycle/main-terminated" ]]; then kill $CHILD_PID; fi; sleep 1; done) &
            wait $CHILD_PID
            if [[ -f "/lifecycle/main-terminated" ]]; then exit 0; fi

networkPolicies:
  database:
    egress:
      - to:
          - ipBlock:
              cidr: 1.1.1.1/32
        ports:
          - port: 3307
            protocol: TCP
  depedencies:
    egress:
      - to:
          - ipBlock:
              cidr: 1.1.1.1/32
        ports:
          - port: 443
            protocol: TCP

hpa:
  app:
    enabled: true
    replicas:
      min: 2
      max: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50

configMaps:
  app:
    BLUE_HEALTH_GO_SRV_PROJECT_ID: prj-blue-s-blue-cluster-13b7
    BLUE_HEALTH_GO_SRV_APP_ENVIRONMENT: staging
    BLUE_HEALTH_GO_SRV_DATABASE_MAX_CONNS: "15"
    BLUE_HEALTH_GO_SRV_DATABASE_CLOUD_NAME: prj-blue-s-blue-cluster-13b7:europe-west3:psql-s-europe-west3-blue-identity-srv-ce5a1dd5
  appInit:
    BLUE_HEALTH_GO_SRV_SEED_APP_ENVIRONMENT: staging
    BLUE_HEALTH_GO_SRV_SEED_PROJECT_ID: prj-blue-s-blue-cluster-13b7
    BLUE_HEALTH_GO_SRV_SEED_DATABASE_MAX_CONNS: "10"
    BLUE_HEALTH_GO_SRV_SEED_DATABASE_CLOUD_NAME: prj-blue-s-blue-cluster-13b7:europe-west3:psql-s-europe-west3-blue-identity-srv-ce5a1dd5
    BLUE_HEALTH_GO_SRV_MIGRATE_APP_ENVIRONMENT: staging
    BLUE_HEALTH_GO_SRV_MIGRATE_PROJECT_ID: prj-blue-s-blue-cluster-13b7
    BLUE_HEALTH_GO_SRV_MIGRATE_TOUCH_FILE: /lifecycle/main-terminated
