{{- range $name, $cm := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ template "project.name" $ }}-{{ kebabcase $name }}
  labels:
    app.kubernetes.io/component: config-map
    {{ include "project.labels" $ | nindent 4 }}
  {{- if (hasSuffix "-init" (kebabcase $name)) }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
  {{- end }}
data:
  {{ toYaml $cm | nindent 2 }}
{{- end }}
