{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: s-{{ template "project.name" . }}
  labels:
    app.kubernetes.io/component: secret
    {{ include "project.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ default "MISSING" $value | b64enc | quote }}
  {{- end }}
{{- end}}
