{{- range $name, $seed := .Values.seeds }}
{{- if $seed.enabled }}
{{- with $seed }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: j-{{ template "project.name" $ }}-{{ $name }}-seeds
  labels:
    app.kubernetes.io/component: seeds
    {{ include "project.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{ toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .annotations }}
    {{ toYaml .annotations | nindent 4 }}
    {{- end }}
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: j-p-{{ template "project.name" $ }}-{{ $name }}-seeds
      labels:
        app.kubernetes.io/component: seeds-pod
        {{ include "project.labels" $ | nindent 8 }}
        {{- if .labels }}
        {{ toYaml .labels | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- if .volumes }}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      shareProcessNamespace: {{ .shareProcessNamespace | default false }}
      containers:
      {{- range $name, $container := .containers }}
      {{- with $container }}
      - name: {{ $name }}
        image: {{ .image.repository }}:{{ .image.tag }}
        imagePullPolicy: {{ .image.pullPolicy | default "Always" }}
        {{- if .command }}
        {{- with .command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end}}
        {{- end}}
        {{- if .args }}
        {{- with .args }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end}}
        {{- end}}
        {{- if .volumeMounts }}
        {{- with .volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if or ($seed.configMap) ($.Values.secrets) }}
        envFrom:
        {{- if $seed.configMap }}
          - configMapRef:
              name: cm-{{ template "project.name" $ }}-{{ kebabcase $seed.configMap }}
        {{- end }}
        {{- if $.Values.secrets }}
          - secretRef:
              name: s-{{ template "project.name" $ }}
        {{- end }}
        {{- end }}
        {{- if .securityContext }}
        {{- with .securityContext }}
        securityContext:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if .resources }}
        {{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ if .serviceAccount -}} {{ .serviceAccount }} {{- else -}} {{ $.Values.serviceAccount }} {{- end }}
{{- end }}
{{- end }}
{{- end }}
