name: Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".local/**"
      - "reference/**"

jobs:
  ci:
    name: CI
    uses: blue-health/blue-health-go-srv/.github/workflows/ci.yml@main
  cd:
    name: CD
    needs: ci
    uses: blue-health/blue-health-go-srv/.github/workflows/cd.yml@main
    with:
      app: blue-health-go-srv
      namespace: my_namespace
      env_suffix: staging
    secrets:
      artifact_region: ${{ secrets.ARTIFACT_REGION }}
      cluster: ${{ secrets.STAGING_CLUSTER }}
      cluster_zone: ${{ secrets.STAGING_CLUSTER_ZONE }}
      cluster_project_id: ${{ secrets.STAGING_CLUSTER_PROJECT_ID }}
      cluster_artifact_repo: ${{ secrets.STAGING_CLUSTER_ARTIFACT_REPO }}
      network_project_id: ${{ secrets.STAGING_NETWORK_PROJECT_ID }}
      network_bastion: ${{ secrets.STAGING_NETWORK_BASTION }}
      network_bastion_zone: ${{ secrets.STAGING_NETWORK_BASTION_ZONE }}
      workload_identity_provider: ${{ secrets.STAGING_WORKLOAD_IDENTITY_PROVIDER }}
      workload_identity_service_account: ${{ secrets.STAGING_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}
      additional_values: |
        secrets:
          # Service
          BLUE_HEALTH_GO_SRV_DATABASE_DSN: ${{ secrets.STAGING_DATABASE_DSN }}
          # Migrations
          BLUE_HEALTH_GO_SRV_MIGRATE_DATABASE_DSN: ${{ secrets.STAGING_DATABASE_DSN }}
